apiVersion: v1
kind: Service
metadata:
  name: medusa
  namespace: medusa
  labels:
    app: medusa
spec:
  type: ClusterIP
  # For local development/testing, use NodePort or LoadBalancer
  # type: NodePort
  # nodePort: 30090
  ports:
  - port: 9000
    targetPort: 9000
    protocol: TCP
    name: http
  selector:
    app: medusa
