apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegram-bot
  namespace: medusa-store
  labels:
    app: telegram-bot
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  progressDeadlineSeconds: 30
  selector:
    matchLabels:
      app: telegram-bot
  template:
    metadata:
      labels:
        app: telegram-bot
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - name: telegram-bot
          image: efirshey/telegram-bot:838872184783a0cdbcf78ae3f8e5a7f5d704de44
          imagePullPolicy: Always
          env:
          - name: BOT_TOKEN
            valueFrom:
              secretKeyRef:
                name: telegram-bot-secrets
                key: BOT_TOKEN
          - name: ADMINS
            valueFrom:
              secretKeyRef:
                name: telegram-bot-secrets
                key: ADMINS
          resources:
            requests:
              memory: "56Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"

